---
- name: GCP
  hosts: all
  vars:
    ansible_ssh_user: 'root'
    ansible_python_interpreter: '/usr/bin/python2'

  tasks:
  - name: Start Mariadb
    service:
      name: mariadb
      state: started

  - shell: whoami && pwd
    register: foo
  - debug: msg="the echo was {{ foo.stdout }}"

  - shell: rm -rf /app
  - shell: git clone https://github.com/simopunkc/final-project-generasi-gigih.git /app
  - shell: mysql -u root < /app/database.sql

  - name: install sinatra systemd
    copy:
      src: /app/sinatra.service
      dest: /etc/systemd/system/sinatra.service
      remote_src: yes

  - name: reload systemd
    systemd:
      daemon_reload: yes

  - name: start sinatra
    systemd:
      name: sinatra
      state: started
      